#POLLS

In [14]:
%run setup.py
from src import cargar_csv

Path del proyecto cargado: C:/Users/Lenovo/Desktop/Escritorio/Datos/python/data/elecciones_usa24
Entorno configurado y variables de entorno cargadas.
Librerías importadas y configuradas correctamente.

In [15]:
may_polls1 = cargar_csv('../elecc_usa24/may_polls/pres_polls_538_may.csv')
may_polls2 = cargar_csv('../elecc_usa24/may_polls/president_polls_rtw.csv')
sep_oct_polls = cargar_csv('../elecc_usa24/sep_oct_polls/538_polls.csv')

In [16]:
from src import nombres_columnas

In [17]:
nombres_columnas(may_polls1)

,day,len,state,ev,dem,gop,ind,date,unnamed:_8,unnamed:_9,unnamed:_10,unnamed:_11,unnamed:_12,unnamed:_13,unnamed:_14,pollster
0,108.0,9,Alabama,9,32,60,NaN,Apr 21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zogby-9
1,61.5,4,Alabama,9,38,57,NaN,Mar 03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Florida Atlantic U.-4
2,108.0,9,Alaska,3,43,50,NaN,Apr 21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zogby-9
3,124.5,12,Arizona,11,43,49,NaN,May 09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Siena Coll.-12
4,118.0,5,Arizona,11,48,52,NaN,Apr 29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emerson Coll.-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,53.0,5,Wisconsin,10,42,45,NaN,Feb 24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emerson Coll.-5
214,47.0,9,Wisconsin,10,42,46,NaN,Feb 20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Morning Consult-9
215,28.0,5,Wisconsin,10,47,47,NaN,Jan 30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Beacon + Shaw for Fox-5
216,27.5,8,Wisconsin,10,47,45,NaN,Jan 31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marquette Law School-8
217,108.0,9,Wyoming,3,26,67,NaN,Apr 21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zogby-9